apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: crime-analysis-kv
    objects: |
      array:
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
    tenantId: "<your_tenant_id>"
