name: CD Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
 - name: Login to Azure
   uses: azure/login@v1
   with:
     client-id: ${{ secrets.AZURE_CLIENT_ID }}
     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
- name: Get OpenAI API Key
  run: |
    OPENAI_API_KEY=$(az keyvault secret show \
      --vault-name crime-analysis-kv \
      --name OPENAI-API-KEY \
      --query value -o tsv)
    echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV
      - name: Get OpenAI API Key from Key Vault
        run: |
          OPENAI_API_KEY=$(az keyvault secret show \
            --vault-name crime-analysis-kv \
            --name OPENAI-API-KEY \
            --query value -o tsv)
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      - name: Deploy to AKS
        run: bash scripts/deploy_to_aks.sh
